name: develop-ci

on:
    pull_request:
        types: [opened, ready_for_review, synchronize]
        branches: [develop]

jobs:
    ci:
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                node-version: [18.13]
        steps:
            - name: Checkout source code
              uses: actions/checkout@v3

            - name: Setup Node ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Environment configuration testing
              env:
                  REACT_APP_KAKAO_KEY: ${{ secrets.REACT_APP_KAKAO_KEY }}
              run: |
                  echo "REACT_APP_KAKAO_KEY" $REACT_APP_KAKAO_KEY

            - name: Install dependencies
              # https://yarnpkg.com/cli/install
              run: yarn

            - name: src/* Build
              run: |
                  yarn build
